global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: "otel"
    static_configs:
      - targets: [ 'otel-collector:8889' ]

  # - job_name: "prometheus"
  #   static_configs:
  #     - targets: [ 'prometheus:9090' ]
