apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    apiVersion: 1
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          name: TraceId
          matcherRegex: \"TraceId\"\:\"(\w+)\"
          url: $${__value.raw}

  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      exemplarTraceIdDestinations:
        - name: TraceId
          datasourceUid: tempo

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3100
    basicAuth: false
    isDefault: false
    version: 1
    uid: tempo
    editable: true
    jsonData:
      tracesToLogs:
        datasourceUid: 'loki'